# Generated by Django 5.2.17 on 2026-09-24 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_hostel_owner_alter_hostel_name'),
        ('rooms', '0002_room_hostel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingtype',
            name='owner',
            field=models.ForeignKey(help_text='The owner account that created this fee tier.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharing_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sharingtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hostel', 'room_number')},
        ),
        migrations.AlterUniqueTogether(
            name='sharingtype',
            unique_together={('owner', 'name')},
        ),
    ]
