# Generated by Django 5.2.17 on 2026-09-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_resident_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Discount deducted from the hostel's base rate for this resident.", max_digits=7),
        ),
    ]
